version: "3.9"  # optional since v1.27.0
services:
  gateway:
    image: nginx
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - api
      - client
    restart: on-failure:30
  api:
    image: node:16-alpine
    command: yarn run start:dev
    working_dir: /code
    volumes:
      - ./server:/code
    ports:
      - 3001:3001
    # networks:
    #   - local
  client:
    image: node:16-alpine
    working_dir: /code
    command: yarn dev --host
    volumes:
      - ./client:/code
    ports:
      - 3000:3000
    # networks:
    #   - local
# networks:
#   local:
#     driver: bridge
  # web:
  #   build: .
  #   ports:
  #     - "8000:5000"
  #   volumes:
  #     - .:/code
  #     - logvolume01:/var/log
  #   links:
  #     - redis
